#xxljob配置
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin #调度器访问地址
    executor:
      appname: intern-job  #对应在xxl-job控制条新增执行器时，填写的APPNAME，执行器心跳注册分组依据
      ip:  #执行器IP默认为空表示自动获取ip
      port: 9998 #执行器的默认端口为9999，port是一个内置的jetty服务端口
      logpath: E:\IdeaProjects\demo\logs  #执行器运行日志文件存储的磁盘位置，需要对该路径拥有读写权限
      logretentiondays: 10 #日志保存日期
    accessToken:
spring:
  mail:
    host: smtp.qq.com
      port: 25
      username: 753173952@qq.com
      password: a770115988
      protocol: smtp
      properties:
        mail:
          smty:
            auth: true
            starttls:
              enable: true
              required: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory