##############################quartz定时任务配置###############################
spring:
  quartz:
    properties: #相关属性配置
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler #quartz名称
            instanceId: AUTO #ID设置为自动获取 每一个必须不同 （所有调度器实例中是唯一的）使用集群：AUTO 不使用集群：NON_CLUSTERED
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX #jobStore事务
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #StdJDBC数据库驱动
            tablePrefix: QRTZ_ #Quartz表前缀
            isClustered: false #是否加入集群
            clusterCheckinInterval: 10000
            useProperties: true #指定序列化的数据是否以Key-Value的形式存储
            acquireTriggersWithinLock: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5 #线程数量
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc #任务信息存储至数据库
    wait-for-jobs-to-complete-on-shutdown: true #等待任务完成后再停止
    auto-startup: true
    startup-delay: 10s
    overwrite-existing-jobs: true #修改配置后使正在运行的Job能够生效
    jdbc:
      initialize-schema: never #初始化表结构  不初始化(好像这个属性不起作用)
#############################################################################