##############################quartz定时任务配置###############################
spring:
  quartz:
    properties: #相关属性配置
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler #quartz名称
            instanceId: AUTO #ID设置为自动获取 每一个必须不同 （所有调度器实例中是唯一的）使用集群：AUTO 不使用集群：NON_CLUSTERED
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX #数据保存方式为持久化
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #StdJDBCDelegate说明支持集群
            tablePrefix: QRTZ_ #Quartz内部表前缀
            isClustered: true #是否加入集群
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
    #初始化表结构
    #jdbc:
    #initialize-schema: never
    wait-for-jobs-to-complete-on-shutdown: true #等待任务完成后再停止
    auto-startup: true
    startup-delay: 10s
#############################################################################