mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml #mybatis配置 *在多个模块的情况下必须要
  type-aliases-package: com.example.demo.enity #实体类别名配置
  executor-type: simple #默认执行器类别
  configuration:
    local-cache-scope: statement #关闭一级缓存
    cache-enabled: false #关闭二级缓存
    map-underscore-to-camel-case: true #驼峰映射配置
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl #sql日志打印
    call-setters-on-nulls: true #不加这个查询数据为空时，字段将被隐藏
  global-config:
    db-config:
      id-type: auto #主键生成策略配置 数据库自增
      #字段策略  新版本中字段策略默认为not_null 所以无需配置
      #insert-strategy: not_null
      #update-strategy: not_null
      #select-strategy: not_null
      logic-delete-value: 1 #逻辑删除值
      logic-not-delete-value: 0 #逻辑非删除值